// front/src/chess/components/Chessboard.vue
<template>
  <div ref="chessboardRef" id="chessboard" class="overflow-hidden select-none touch-action-none" @mousemove="movePiece"
    @mousedown="grabPiece" @mouseup="dropPiece" @touchstart="handleTouch($event); grabPiece($event)"
    @touchmove="handleTouch($event); movePiece($event)" @touchend="handleTouch($event); dropPiece($event)"
    @contextmenu.prevent>
    <Square v-for="(square, index) in board" :key="index" :isWhite="square.isWhite" :piece="square.piece"
      :highlight="square.highlight" :drag="square.drag" />
    <div class="chessboard-nav">
      <!-- Navigation buttons or additional content can go here -->
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";
import Square from "./Square.vue";
import { row, column } from "../Constants";
import { Position } from "../models";
import type { PropType } from "vue";

export default defineComponent({
  name: "Chessboard",
  components: { Square },
  props: {
    playMove: {
      type: Function as PropType<
        (piece: any, destination: Position, chessboard: HTMLElement) => boolean
      >,
      required: true,
    },
    pieces: {
      type: Array as PropType<any[]>,
      required: true,
    },
    setOrientation: {
      type: Function as PropType<(orientation: string) => void>,
      required: true,
    },
    getOrientation: {
      type: Function as PropType<() => string>,
      required: true,
    },
    teamTurn: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const activePiece = ref<HTMLElement | null>(null);
    const grabPosition = ref<Position | null>(null);
    const isDragging = ref(false);
    const chessboardRef = ref<HTMLElement | null>(null);

    // Helper: get board bounding rectangle
    const getBoardRect = () => {
      return chessboardRef.value?.getBoundingClientRect() || { left: 0, top: 0, width: 0, height: 0 };
    };

    const handleTouch = (e: TouchEvent) => {
      e.stopPropagation();
    };

    // Revised grabPiece:
    const grabPiece = (e: MouseEvent | TouchEvent) => {
      const chessboard = chessboardRef.value;
      if (!chessboard) return;

      // Use closest() so clicking on a child still selects the piece.
      const element = (e.target as HTMLElement).closest(".piece") as HTMLElement;
      if (!element || !element.classList.contains("drag")) return;

      let clientX = 0, clientY = 0;
      if (e.type === "touchstart") {
        isDragging.value = true;
        clientX = (e as TouchEvent).touches[0].clientX;
        clientY = (e as TouchEvent).touches[0].clientY;
      } else {
        clientX = (e as MouseEvent).clientX;
        clientY = (e as MouseEvent).clientY;
      }

      const rect = getBoardRect();
      const cellSize = rect.height / 8; // Since board is 80vmin and 8 rows → 10vmin each

      // We leave the piece's CSS size as defined (10vmin in your CSS).
      element.style.position = "absolute";
      element.style.zIndex = "999";
      element.style.left = `${clientX - cellSize / 2}px`;
      element.style.top = `${clientY - cellSize / 2}px`;

      // For white orientation, row index = 7 - floor((clientY - top) / cellSize)
      const relativeX = clientX - rect.left;
      const relativeY = clientY - rect.top;
      const colIndex = Math.floor(relativeX / cellSize);
      const rowIndexWhite = 7 - Math.floor(relativeY / cellSize);

      grabPosition.value =
        props.getOrientation() === "white"
          ? new Position(colIndex, rowIndexWhite)
          : new Position(7 - colIndex, 7 - rowIndexWhite);

      activePiece.value = element;
    };

    const movePiece = (e: MouseEvent | TouchEvent) => {
      const chessboard = chessboardRef.value;
      if (!activePiece.value || !chessboard) return;
      const rect = getBoardRect();
      let clientX = 0, clientY = 0;
      if (isDragging.value) {
        clientX = (e as TouchEvent).touches[0].clientX;
        clientY = (e as TouchEvent).touches[0].clientY;
      } else {
        clientX = (e as MouseEvent).clientX;
        clientY = (e as MouseEvent).clientY;
      }
      const cellSize = rect.height / 8;
      const clampedX = Math.max(rect.left, Math.min(clientX, rect.left + rect.width));
      const clampedY = Math.max(rect.top, Math.min(clientY, rect.top + rect.height));
      activePiece.value.style.left = `${clampedX - cellSize / 2}px`;
      activePiece.value.style.top = `${clampedY - cellSize / 2}px`;
    };

    const dropPiece = (e: MouseEvent | TouchEvent) => {
      const chessboard = chessboardRef.value;
      if (!activePiece.value || !chessboard || !grabPosition.value) return;
      const rect = getBoardRect();
      let clientX = 0, clientY = 0;
      if (isDragging.value) {
        clientX = (e as TouchEvent).changedTouches[0].clientX;
        clientY = (e as TouchEvent).changedTouches[0].clientY;
      } else {
        clientX = (e as MouseEvent).clientX;
        clientY = (e as MouseEvent).clientY;
      }
      const cellSize = rect.height / 8;
      let col = Math.floor((clientX - rect.left) / cellSize);
      let rowWhite = 7 - Math.floor((clientY - rect.top) / cellSize);
      let finalPos = props.getOrientation() === "white"
        ? new Position(col, rowWhite)
        : new Position(7 - col, 7 - rowWhite);

      const currentPiece = props.pieces.find(p => p.samePosition(grabPosition.value));
      if (currentPiece) {
        const moveSuccessful = props.playMove(currentPiece, finalPos, chessboard);
        if (!moveSuccessful) {
          activePiece.value.style.removeProperty("top");
          activePiece.value.style.removeProperty("left");
        }
        activePiece.value.style.zIndex = "0";
        activePiece.value = null;
        isDragging.value = false;
      }
    };

    // Keep renderBoard unchanged from before
    const renderBoard = () => {
      const boardArray = [];
      let white_square = false;
      let jStart, jEnd, jIncrement, iStart, iEnd, iIncrement;
      if (props.getOrientation() === "white") {
        jStart = row.length - 1;
        jEnd = -1;
        jIncrement = -1;
        iStart = 0;
        iEnd = column.length;
        iIncrement = 1;
      } else {
        jStart = 0;
        jEnd = row.length;
        jIncrement = 1;
        iStart = column.length - 1;
        iEnd = -1;
        iIncrement = -1;
      }
      for (let j = jStart; j !== jEnd; j += jIncrement) {
        white_square = !white_square;
        for (let i = iStart; i !== iEnd; i += iIncrement) {
          const piece = props.pieces.find(p => p.samePosition(new Position(i, j)));
          const image = piece ? piece.image : undefined;
          const currentPiece = activePiece.value
            ? props.pieces.find(p => p.samePosition(grabPosition.value))
            : undefined;
          let highlight = currentPiece?.possibleMoves
            ? currentPiece.possibleMoves.some((p: Position) => p.samePosition(new Position(i, j)))
            : false;
          if (!highlight && currentPiece?.isPawn && piece?.isPawn) {
            const enPassantPiece =
              piece.enPassant &&
              piece.team !== currentPiece.team &&
              Math.abs(piece.position.x - currentPiece.position.x) === 1 &&
              piece.position.y === currentPiece.position.y;
            if (enPassantPiece) highlight = true;
          }
          const drag = piece?.team === props.teamTurn;
          boardArray.push({
            isWhite: white_square,
            piece: image,
            highlight,
            drag,
          });
          white_square = !white_square;
        }
      }
      return boardArray;
    };

    const board = computed(() => renderBoard());

    return {
      chessboardRef,
      movePiece,
      grabPiece,
      dropPiece,
      handleTouch,
      board,
    };
  },
});
</script>

<style scoped>
#chessboard {
  height: 80vmin;
  width: 80vmin;
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  grid-template-rows: repeat(8, 1fr);
  outline: none;
  background-color: #94242E;
  touch-action: none;
  overflow: hidden;
}

#chessboard:hover {
  cursor: pointer;
}

.squareHighlight {
  position: relative;
  outline: none;
  display: flex;
  justify-content: center;
  align-items: center;
}

.squareHighlight::before {
  content: "";
  width: 3vmin;
  height: 3vmin;
  box-shadow: inset 0 0 3vmin 3vmin rgba(0, 0, 0, 0.5);
  border-radius: 50%;
}

.squareHighlightOccupied {
  border-radius: 3vmin;
}

@media screen and (max-width:768px) {
  #chessboard {
    height: 80vmin;
    width: 80vmin;
    grid-template-columns: repeat(8, 1fr);
    grid-template-rows: repeat(8, 1fr);
  }

  .piece {
    width: 10vmin;
    height: 10vmin;
  }
}
</style>

// front/src/chess/components/Chessboard/Chessboard.jsx
import React, { useRef, useState } from 'react';
import Square from '../Square/Square';
import './Chessboard.css';
import { row, column } from '../../Constants';
import { Position } from "../../models";




export default function Chessboard({ playMove, pieces, setOrientation, getOrientation, teamTurn }) {
    // Initialization
    const [activePiece, setActivePiece] = useState(null);
    const [grabPosition, setGrabPosition] = useState(null);
    const [isDragging, setIsDragging] = useState(false); // mobile
    const chessboardRef = useRef(null);



    function handleTouch(e) {
        e.stopPropagation(); // Prevent touch event from bubbling up the DOM tree
    }


    /**
     * Grab the piece and center it on the cursor
     * 
     * @param {event} e 
     * 
     * @returns {element} Grabbed piece element
     */

    function grabPiece(e) {
        const chessboard = chessboardRef.current;
        const element = e.target;
        let x = 0;
        let y = 0;
    
        if (element.classList.contains("piece") && element.classList.contains("drag") && chessboard) {
            // mobile
            if (e.type === "touchstart") {
                setIsDragging(true); // mobile
                x = e.touches[0].clientX;
                y = e.touches[0].clientY;
            }
            // browser
            else {
                x = e.clientX;
                y = e.clientY;
            }
    
            // Get the dimensions of the image
            const width = element.offsetWidth;
            const height = element.offsetHeight;
    
            // Calculate the left and top positions to center the image on the cursor
            const left = x - (width / 2);
            const top = y - (height / 2);
    
            // Set the position and size of the image
            element.style.position = "absolute";
            element.style.zIndex = 999;
            element.style.left = `${left}px`;
            element.style.top = `${top}px`;
    
            // Adjust grab position based on board orientation
            const grabX = Math.floor((x - chessboard.offsetLeft) / (chessboard.clientHeight / row.length));
            const grabY = Math.abs(Math.ceil((y - chessboard.offsetTop - chessboard.clientHeight) / (chessboard.clientHeight / column.length)));
            setGrabPosition(
                getOrientation() === "white"
                    ? new Position(grabX, grabY)
                    : new Position(column.length - 1 - grabX, row.length - 1 - grabY)
            );
    
            setActivePiece(element);
        }
    }   
    
    
    /**
     * Grabbed piece follows the cursor
     * @param {event} e 
     */
    function movePiece(e) {
        const chessboard = chessboardRef.current;
        if (activePiece && chessboard) {
            // chessboard corner offsets
            const minX = chessboard.offsetLeft;
            const minY = chessboard.offsetTop;
            const maxX = chessboard.offsetLeft + chessboard.clientWidth;
            const maxY = chessboard.offsetTop + chessboard.clientHeight;

            let x = grabPosition.x;
            let y = grabPosition.y;

            if (isDragging) { // mobile
                x = e.touches[0].clientX;
                y = e.touches[0].clientY;
            } else {
                // cursor coordinates
                x = e.clientX;
                y = e.clientY;
            }

            // Get the dimensions of the image
            const width = activePiece.offsetWidth;
            const height = activePiece.offsetHeight;

            // Calculate the left and top positions to center the image on the cursor
            const left = x - (width / 2);
            const top = y - (height / 2);

            // Set the center of the image on the cursor
            activePiece.style.left = x  < minX ? `${minX - width / 2}px` : x > maxX ? `${maxX - width / 2}px` : `${left}px`;
            activePiece.style.top = y  < minY ? `${minY - height / 2}px` : y > maxY ? `${maxY - height / 2}px` : `${top}px`;
        }
    }
    /**
     * Checks if the move is a valid, updates the board state
     * @param {event} e 
     */
    function dropPiece(e) {
        const chessboard = chessboardRef.current;

        if (activePiece && chessboard) {
            let x = grabPosition.x;
            let y = grabPosition.y;
            if (isDragging) { // mobile
                x = Math.floor((e.changedTouches[0].clientX - chessboard.offsetLeft) / (chessboard.clientHeight / row.length));
                y = Math.abs(Math.ceil((e.changedTouches[0].clientY - chessboard.offsetTop - chessboard.clientHeight) / (chessboard.clientHeight / column.length)));
            } else {
                // Get the square coordinates 
                x = Math.floor((e.clientX - chessboard.offsetLeft) / (chessboard.clientHeight / row.length));
                y = Math.abs(Math.ceil((e.clientY - chessboard.offsetTop - chessboard.clientHeight) / (chessboard.clientHeight / column.length)));
            }
            
            // Update the grabbed position based on the orientation of the board
            if (getOrientation() === 'black') {
                x = column.length - 1 - x;
                y = row.length - 1 - y;
            }
            // Get the dropped piece 
            const currentPiece = pieces.find(p => p.samePosition(grabPosition));

            if (currentPiece) {
                if (!playMove(currentPiece, new Position(x, y), chessboard)) {
                    // If this is not a valid move place the piece to its last position
                    activePiece.style.removeProperty('top');
                    activePiece.style.removeProperty('left');
                }

                activePiece.style.zIndex = 0;
                setActivePiece(null); // The dropped piece doesnt follow the cursor anymore
                setIsDragging(false); // mobile
                
            }
        }
    }

    function renderBoard() {
        let board = [];
        let white_square = false;
        let jStart, jEnd, jIncrement, iStart, iEnd, iIncrement;

        if (getOrientation() === 'white') {
            jStart = row.length - 1;
            jEnd = -1;
            jIncrement = -1;
            iStart = 0;
            iEnd = column.length;
            iIncrement = 1;
        } else {
            jStart = 0;
            jEnd = row.length;
            jIncrement = 1;
            iStart = column.length - 1;
            iEnd = -1;
            iIncrement = -1;
        }

        for (let j = jStart; j !== jEnd; j += jIncrement) {
            white_square = !white_square;
            for (let i = iStart; i !== iEnd; i += iIncrement) {
                const piece = pieces.find(p => p.samePosition(new Position(i, j)))
                let image = piece ? piece.image : undefined;
                // Search the grabbed piece
                let currentPiece = activePiece != null ? pieces.find(p => p.samePosition(grabPosition)) : undefined;
                // Highlight validmoves
                let highlight = currentPiece?.possibleMoves ? currentPiece.possibleMoves.some(p => p.samePosition(new Position(i, j))) : false;
                // Highlight pawn taken enPassant
                if (!highlight && currentPiece?.isPawn && piece?.isPawn) {
                    const enPassantPiece = piece.enPassant &&
                        piece.team !== currentPiece.team &&
                        Math.abs(piece.position.x - currentPiece.position.x) === 1 &&
                        piece.position.y === currentPiece.position.y;;
                    if (enPassantPiece)
                        highlight = true;
                }
                // Set drag on team turn pieces
                let drag = piece?.team === teamTurn;                

                board.push(<Square key={`${j},${i}`} isWhite={white_square} piece={image} highlight={highlight} drag={drag} index={`${j},${i}`} />);
                white_square = !white_square;
            }
        }

        return board;
    }

    // Toggle board orientation
    function rotateBoard() {
        getOrientation() === 'white' ? setOrientation('black') : setOrientation('white');
    }
    function righClick(e){
        e.preventDefault();
    }

    const board = renderBoard();

    return (

        <div
            onMouseMove={e => movePiece(e)}
            onMouseDown={e => grabPiece(e)}
            onMouseUp={e => dropPiece(e)}
            onTouchStart={e => {
                handleTouch(e);
                grabPiece(e);
            }}
            onTouchMove={e => {
                handleTouch(e);
                movePiece(e);
            }}
            onTouchEnd={e => {
                handleTouch(e);
                dropPiece(e);
            }}
            onContextMenu={e => righClick(e)}
            ref={chessboardRef}
            id="chessboard"
        >

            {board}
            <div className="chessboard-nav">
                
            </div>
        </div>
    );
}
//<button onClick={rotateBoard}>Rotate Board</button>
